INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (1, 1, 'yī', 'one', 'единица', '一');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (2, 2, 'gǔn', 'line', 'вертикаль', '丨');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (3, 3, 'zhǔ', 'stroke', 'точка', '丶');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (4, 4, 'fú', 'oblique', 'откидная', '丿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (5, 5, 'yǐ', 'sickle', 'и, второй', '乙');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (6, 6, 'jué', 'hook', 'крюк', '亅');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (7, 7, 'èr', 'two', 'два', '二');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (8, 8, 'tóu', 'shelter, head', 'крышка', '亠');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (9, 9, 'rén', 'man', 'человек', '人');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (10, 10, 'er', 'child', 'ноги', '儿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (11, 11, 'rù', 'to enter', 'входить', '入');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (12, 12, 'bā', 'eight', 'восемь', '八');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (13, 13, 'jiōng', 'scope', 'земли далеко за городом', '冂');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (14, 14, 'mì', 'to cover', 'покрывало', '冖');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (15, 15, 'bīng', 'ice', 'лед', '冫');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (16, 16, 'jǐ', 'table', 'столик', '几');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (17, 17, 'qiǎn', 'container', 'раскрытый рот', '凵');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (18, 18, 'dāo', 'knife', 'нож', '刀');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (19, 19, 'lì', 'force', 'сила', '力');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (20, 20, 'bāo', 'to wrap', 'завертывать', '勹');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (21, 21, 'bǐ', 'spoon, man overthrown', 'черпак', '匕');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (22, 22, 'fāng', 'open box', 'ящик', '匚');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (23, 23, 'xì', 'to hide', 'прятать', '匸');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (24, 24, 'shí', 'ten', 'десять', '十');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (25, 25, 'bo', 'divination', 'гадание', '卜');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (26, 26, 'jié', 'seal', 'печать', '卩');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (27, 27, 'chǎng', 'production facility', 'обрыв', '厂');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (28, 28, 'sī', 'secret', 'частный', '厶');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (29, 29, 'yòu', 'still', 'снова', '又');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (30, 30, 'kǒu', 'mouth', 'рот', '口');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (31, 31, 'wéi', 'enclosure', 'территория с границами', '囗');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (32, 32, 'tǔ', 'earth', 'земля', '土');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (33, 33, 'shì', 'scholar', 'ученый муж', '士');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (34, 34, 'zhǐ', 'to go', 'ходить', '夂');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (35, 35, 'suī', 'go slowly', 'медленно идти', '夊');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (36, 36, 'xī', 'evening', 'вечер', '夕');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (37, 37, 'dà', 'big', 'большой', '大');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (38, 38, 'nǚ', 'woman', 'женщина', '女');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (39, 39, 'zi', 'child', 'ребенок', '子');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (40, 40, 'mián', 'roof', 'крыша', '宀');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (41, 41, 'cùn', 'thumb', 'цунь, вершок', '寸');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (42, 42, 'xiǎo', 'small', 'маленький', '小');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (43, 43, 'yóu', 'weak', 'хилый', '尢');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (44, 44, 'shī', 'dead body', 'труп', '尸');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (45, 45, 'chè', 'germ', 'росток', '屮');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (46, 46, 'shān', 'mountain', 'гора', '山');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (47, 47, 'chuān', 'river', 'река', '川');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (48, 48, 'gōng', 'work', 'работа', '工');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (49, 49, 'jǐ', 'personal', 'сам', '己');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (50, 50, 'jīn', 'turban', 'платок', '巾');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (51, 51, 'gàn', 'dry', 'сухой', '干');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (52, 52, 'yāo', 'tiny', 'нитка', '幺');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (53, 53, 'guǎng', 'shelter', 'широкий', '广');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (54, 54, 'yǐn', 'great, stride', 'тянуть', '廴');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (55, 55, 'gǒng', 'two, hands', 'две руки', '廾');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (56, 56, 'yì', 'arrow-grapin', 'стрелять из лука', '弋');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (57, 57, 'gōng', 'bow', 'лук', '弓');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (58, 58, 'jì', 'snout', 'свиная голова', '彐');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (59, 59, 'shān', 'beard, brush', 'волосы', '彡');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (60, 60, 'chì', 'walk around', 'шаг', '彳');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (61, 61, 'xīn', 'heart', 'сердце', '心');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (62, 62, 'gē', 'halberd', 'копье', '戈');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (63, 63, 'hù', 'gate', 'двор', '户');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (64, 64, 'shǒu', 'hand', 'рука', '手');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (65, 65, 'zhī', 'branch', 'ветка', '支');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (66, 66, 'pū', 'to bump, hand', 'ударять палкой', '攴');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (67, 67, 'wén', 'writing', 'письмо', '文');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (68, 68, 'dòu', 'measurer', 'ковш', '斗');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (69, 69, 'jīn', 'ax, 500 grams', 'топор', '斤');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (70, 70, 'fāng', 'square, direction', 'квадрат', '方');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (71, 71, 'wú', 'without', 'не', '无');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (72, 72, 'rì', 'sun', 'солнце', '日');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (73, 73, 'yuē', 'to say', 'говорить', '曰');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (74, 74, 'yuè', 'moon', 'луна', '月');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (75, 75, 'mù', 'tree', 'дерево', '木');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (76, 76, 'qiàn', 'tired', 'недоставать', '欠');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (77, 77, 'zhǐ', 'to stop', 'остановиться', '止');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (78, 78, 'dǎi', 'death', 'плохой, злой', '歹');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (79, 79, 'shū', 'weapon', 'пика', '殳');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (80, 80, 'mǔ', 'mother', 'не надо', '毋');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (81, 81, 'bǐ', 'to confront', 'сравнивать', '比');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (82, 82, 'máo', 'fur', 'шерсть', '毛');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (83, 83, 'shì', 'clan', 'клан', '氏');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (84, 84, 'qì', 'air', 'пар', '气');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (85, 85, 'shuǐ', 'water', 'вода', '水');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (86, 86, 'huǒ', 'fire', 'огонь', '火');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (87, 87, 'zhǎo', 'claw', 'claw', '爪');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (88, 88, 'fù', 'father', 'отец', '父');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (89, 89, 'yáo', 'double', 'диаграммы', '爻');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (90, 90, 'pán', 'splitted, wood', 'половина дерева', '爿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (91, 91, 'piàn', 'slice', 'щепка', '片');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (92, 92, 'yá', 'tooth, ivory', 'зуб, клык', '牙');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (93, 93, 'niú', 'beef', 'корова', '牛');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (94, 94, 'quǎn', 'dog', 'собака', '犬');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (95, 95, 'xuán', 'deep', 'черный', '玄');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (96, 96, 'yù', 'jade', 'нефрит', '玉');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (97, 97, 'guā', 'melon', 'дыня', '瓜');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (98, 98, 'wǎ', 'tile', 'черепица', '瓦');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (99, 99, 'gān', 'sweet', 'сладкий', '甘');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (100, 100, 'shēng', 'be born', 'жизнь', '生');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (101, 101, 'yòng', 'to use', 'использовать', '用');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (102, 102, 'tián', 'field', 'поле', '田');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (103, 103, 'pǐ', 'roll, piece of cloth', 'кусок ткани', '疋');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (104, 104, 'nè', 'disease', 'болезнь', '疒');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (105, 105, 'bō', 'to go up', 'ноги врозь', '癶');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (106, 106, 'bái', 'white', 'белый', '白');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (107, 107, 'pí', 'skin', 'кожица, кожа', '皮');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (108, 108, 'mǐn', 'container', 'сосуд', '皿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (109, 109, 'mù', 'eye', 'глаз', '目');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (110, 110, 'máo', 'spear', 'копье', '矛');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (111, 111, 'shǐ', 'arrow', 'стрела', '矢');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (112, 112, 'shí', 'stone', 'камень', '石');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (113, 113, 'shì', 'to venerate, to show', 'алтарь', '示');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (114, 114, 'róu', 'get away', 'след зверя', '禸');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (115, 115, 'hé', 'grain', 'злаки', '禾');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (116, 116, 'xué', 'cave, swing door', 'пещера', '穴');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (117, 117, 'lì', 'standing up', 'стоять', '立');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (118, 118, 'shì', 'bamboo', 'бамбук', '竹');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (119, 119, 'mǐ', 'rice', 'рис', '米');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (120, 120, 'mì', 'silk', 'нить, шелк', '纟');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (121, 121, 'fǒu', 'jar', 'амфора', '缶');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (122, 122, 'wǎng', 'net', 'сеть', '网');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (123, 123, 'yáng', 'sheep', 'баран', '羊');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (124, 124, 'yǔ', 'feather', 'перо', '羽');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (125, 125, 'lǎo', 'old', 'старый', '老');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (126, 126, 'ér', 'and', 'и, а', '而');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (127, 127, 'lěi', 'plow', 'плуг', '耒');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (128, 128, 'ěr', 'ear', 'ухо', '耳');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (129, 129, 'yù', 'brush', 'кисть', '聿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (130, 130, 'ròu', 'meat', 'мясо', '肉');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (131, 131, 'chén', 'minister', 'министр, чиновник', '臣');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (132, 132, 'zì', 'personal', 'сам', '自');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (133, 133, 'zhì', 'to reach', 'прибывать', '至');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (134, 134, 'jiù', 'mortar', 'ступка', '臼');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (135, 135, 'shé', 'tongue', 'язык', '舌');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (136, 136, 'chuǎn', 'to oppose', 'ошибка', '舛');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (137, 137, 'zhōu', 'boat', 'лодка', '舟');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (138, 138, 'gěn', 'decided', 'гэнь, остановка', '艮');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (139, 139, 'sè', 'color', 'цвет', '色');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (140, 140, 'cao', 'vegetable', 'трава', '艸');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (141, 141, 'hū', 'tiger', 'тигр', '虍');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (142, 142, 'chóng', 'insect', 'насекомое', '虫');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (143, 143, 'xuè', 'blood', 'кровь', '血');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (144, 144, 'xíng', 'circulate', 'ходить', '行');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (145, 145, 'yī', 'cloth', 'одежда', '衣');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (146, 146, 'xi', 'lid', 'покрывать', '襾');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (147, 147, 'jiàn', 'to see', 'видеть', '见');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (148, 148, 'jiǎo', 'horn', 'рог', '角');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (149, 149, 'yán', 'speech (trad)', 'речь', '讠');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (150, 150, 'gǔ', 'valley', 'долина', '谷');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (151, 151, 'dòu', 'pea', 'боб', '豆');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (152, 152, 'chù', 'pig', 'свинья', '豕');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (153, 153, 'zhì', 'feline, cat family', 'пресмыкающееся', '豸');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (154, 154, 'bèi', 'shell, money', 'ракушка', '贝');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (155, 155, 'chì', 'red', 'красный', '赤');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (156, 156, 'zǒu', 'to walk', 'уходить', '走');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (157, 157, 'zú', 'foot', 'нога', '足');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (158, 158, 'shēn', 'body', 'тело', '身');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (159, 159, 'chē', 'car', 'повозка', '车');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (160, 160, 'xīn', 'bitter', 'горький', '辛');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (161, 161, 'chén', 'morning', 'утро', '辰');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (162, 162, 'chuò', 'brisk walking', 'ходить', '辵');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (163, 163, 'fù', 'city', 'город', '邑');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (164, 164, 'yǒu', 'alcohol', 'ю, десятый знак', '酉');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (165, 165, 'biàn', 'to distinguish', 'различать', '釆');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (166, 166, 'lǐ', 'neighborhood', 'ли, деревня', '里');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (167, 167, 'jīn', 'gold, metal', 'золото', '金');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (168, 168, 'zhǎng', 'long', 'длинный', '长');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (169, 169, 'mén', 'gate', 'ворота, двери', '门');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (170, 170, 'fù', 'mound', 'холм', '阜');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (171, 171, 'lì', 'servant', 'слуга', '隶');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (172, 172, 'zhuī', 'short-tailed bird', 'птица с коротким хвостом', '隹');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (173, 173, 'yǔ', 'rain', 'дождь', '雨');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (174, 174, 'qīng', 'blue/green', 'голубой, зеленый', '青');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (175, 175, 'fēi', 'false', 'не', '非');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (176, 176, 'miàn', 'face', 'лицо', '面');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (177, 177, 'gé', 'leather', 'шкура, кожа', '革');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (178, 178, 'wéi', 'tanned leather', 'выделанная кожа', '韦');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (179, 179, 'jiǔ', 'leek', 'душистый лук', '韭');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (180, 180, 'yīn', 'sound', 'звук', '音');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (181, 181, 'yè', 'head, leaf', 'лист', '页');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (182, 182, 'fēng', 'wind', 'ветер', '风');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (183, 183, 'fēi', 'to fly', 'летать', '飞');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (184, 184, 'shí', 'to eat', 'есть, еда', '食');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (185, 185, 'shǒu', 'head', 'голова', '首');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (186, 186, 'xiāng', 'perfume', 'благоухающий', '香');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (187, 187, 'mǎ', 'horse', 'лошадь', '马');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (188, 188, 'gǔ', 'bone', 'кость', '骨');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (189, 189, 'gāo', 'high', 'высокий', '高');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (190, 190, 'biāo', 'hair', 'волосы', '髟');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (191, 191, 'dòu', 'fight', 'драться', '斗');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (192, 192, 'chàng', 'sacrificial wine', 'вино для жертвоприношений', '鬯');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (193, 193, 'gé', 'cauldron', 'треножник', '鬲');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (194, 194, 'guǐ', 'ghost', 'дух', '鬼');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (195, 195, 'yú', 'fish', 'рыба', '鱼');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (196, 196, 'niǎo', 'bird', 'птица', '鸟');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (197, 197, 'lǔ', 'salt', 'соль', '卤');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (198, 198, 'lù', 'deer', 'олень', '鹿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (199, 199, 'mài', 'corn', 'пшеница', '麦');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (200, 200, 'má', 'hemp', 'конопля', '麻');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (201, 201, 'huáng', 'yellow', 'желтый', '黃');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (202, 202, 'shǔ', 'millet', 'просо', '黍');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (203, 203, 'hēi', 'black', 'черный', '黑');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (204, 204, 'zhǐ', 'embroidery', 'вышивка', '黹');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (205, 205, 'miǎn', 'frog', 'лягушка', '黾');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (206, 206, 'dǐng', 'tripod', 'треножник дин', '鼎');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (207, 207, 'gǔ', 'drum', 'барабан', '鼓');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (208, 208, 'shǔ', 'rat', 'мышь', '鼠');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (209, 209, 'bí', 'nose', 'нос', '鼻');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (210, 210, 'qí', 'regular', 'ровный, равный', '齐');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (211, 211, 'chǐ', 'tooth, engrenage', 'зубы', '齿');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (212, 212, 'lóng', 'dragon', 'дракон', '龙');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (213, 213, 'guī', 'tortoise', 'черепаха', '龟');
INSERT INTO hyeroglyph (id, code, transcription, translation_EN, translation_RU, chinese_key) VALUES (214, 214, 'yuè', 'flute', 'флейта', '龠');